"use client";

import { Suspense, useEffect } from "react";
import { useSearchParams } from "next/navigation";

import {
  getPotentialRisks,
  getImmediateActions,
  getFuneralTypeGuidance,
  getSituationOverview,
  getKeyConcerns,
  getRecommendedNextAction,
} from "@/lib/planning-guide/decisionEngine";

export default function PrintPage() {
  return (
    <Suspense fallback={<div className="p-10">Loading funeral plan...</div>}>
      <PrintFuneralPlan />
    </Suspense>
  );
}

function PrintFuneralPlan() {
  const searchParams = useSearchParams();

  const inputs = {
    deathLocation: searchParams.get("deathLocation") || "",
    province: searchParams.get("province") || "",
    urgency: searchParams.get("urgency") || "",
    funeralCover: searchParams.get("funeralCover") || "",
    funeralType: searchParams.get("funeralType") || "",
  };

  useEffect(() => {
    setTimeout(() => {
      window.print();
    }, 500);
  }, []);

  return (
    <main id="print-plan" className="bg-white p-10 text-[#1E3D34]">
      <header className="mb-8 border-b pb-4">
        <h1 className="text-3xl font-bold">Funeral Insights</h1>
        <p className="mt-2 text-[#4B5B55]">
          Personal Funeral Plan
        </p>
      </header>

      <section>
        <h2 className="text-4xl font-bold">
          Your Personal Funeral Plan
        </h2>

        <p className="mt-3 text-[#4B5B55]">
          Generated to help you understand the next steps and make informed
          funeral decisions.
        </p>
      </section>

      <PrintSection title="Funeral Plan">
        <p><strong>Where it happened:</strong> {inputs.deathLocation}</p>
        <p><strong>Province:</strong> {inputs.province}</p>
        <p><strong>Urgency:</strong> {inputs.urgency}</p>
        <p><strong>Funeral cover:</strong> {inputs.funeralCover}</p>
        <p><strong>Funeral type:</strong> {inputs.funeralType}</p>
      </PrintSection>

      <PrintSection title="Assessment">
        <p>{getSituationOverview(inputs)}</p>
      </PrintSection>

      {getKeyConcerns(inputs).length > 0 && (
        <PrintListSection title="Key Concerns" items={getKeyConcerns(inputs)} />
      )}

      <PrintSection title="Recommended Next Action">
        <p className="font-semibold">
          {getRecommendedNextAction(inputs)}
        </p>
      </PrintSection>

      <PrintListSection
        title="Immediate Actions"
        items={getImmediateActions(inputs)}
      />

      <PrintListSection
        title="Funeral Type Guidance"
        items={getFuneralTypeGuidance(inputs)}
      />

      <PrintListSection
        title="Questions to Ask Funeral Providers"
        items={[
          "What is included in the quoted price?",
          "Are removal, storage and transport included?",
          "Are there extra costs not shown in the quote?",
          "When is payment required?",
          "Can I get the quote in writing?",
        ]}
      />

      {getPotentialRisks(inputs).length > 0 && (
        <PrintListSection
          title="Potential Risks to Watch"
          items={getPotentialRisks(inputs)}
        />
      )}

      <footer className="mt-10 border-t pt-4 text-sm text-[#4B5B55]">
        Generated by Funeral Insights South Africa.
      </footer>
    </main>
  );
}

function PrintSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-8 rounded-xl border p-6">
      <h3 className="text-2xl font-bold">{title}</h3>
      <div className="mt-4 space-y-2 leading-7 text-[#4B5B55]">
        {children}
      </div>
    </section>
  );
}

function PrintListSection({
  title,
  items,
}: {
  title: string;
  items: string[];
}) {
  return (
    <section className="mt-8 rounded-xl border p-6">
      <h3 className="text-2xl font-bold">{title}</h3>
      <ul className="mt-4 list-disc space-y-2 pl-5 leading-7 text-[#4B5B55]">
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </section>
  );
}